import type {
  ExerciseDefinition,
  WorkoutDay,
  WorkoutDayId,
} from '@/types/workout';
function exercise(
  id: string,
  name: string,
  sets: number,
  minReps: number,
  maxReps: number,
  restSeconds: number,
  instructions: string,
  options: Partial<ExerciseDefinition> = {},
): ExerciseDefinition {
  return {
    id,
    name,
    sets,
    minReps,
    maxReps,
    restSeconds,
    instructions,
    targetUnit: 'reps',
    unilateral: false,
    rir: 3,
    videoUrl: null,
    trackOneRM: true,
    ...options,
  };
}
export const ROUTINE_VERSION = '1.0.0';
export const ROUTINE_PHASE = 'Semanas 1–4';
export const workoutDays: Record<WorkoutDayId, WorkoutDay> = {
  'day-1': {
    id: 'day-1',
    label: 'Día 1',
    name: 'Full Body A',
    exercises: [
      exercise(
        'leg-press',
        'Prensa inclinada',
        3,
        8,
        10,
        120,
        'Apoya toda la planta del pie. Baja de forma controlada sin despegar la pelvis del respaldo.',
      ),
      exercise(
        'db-bench',
        'Press banca con mancuernas',
        3,
        8,
        10,
        120,
        'Mantén los pies apoyados y los omóplatos estables. Baja las mancuernas con control.',
      ),
      exercise(
        'lat-pulldown',
        'Jalón al pecho',
        3,
        8,
        12,
        120,
        'Lleva los codos hacia abajo y la barra hacia la parte alta del pecho, sin balancearte.',
      ),
      exercise(
        'db-rdl',
        'Peso muerto rumano con mancuernas',
        2,
        8,
        10,
        120,
        'Lleva la cadera hacia atrás con rodillas ligeramente flexionadas y espalda neutra.',
      ),
      exercise(
        'lateral-raise',
        'Elevaciones laterales',
        2,
        12,
        15,
        60,
        'Eleva los brazos hasta la altura de los hombros con los codos ligeramente flexionados.',
        { trackOneRM: false },
      ),
      exercise(
        'pallof',
        'Pallof press',
        2,
        10,
        12,
        60,
        'Resiste la rotación al extender los brazos. Completa las repeticiones en ambos lados.',
        { unilateral: true, trackOneRM: false },
      ),
    ],
  },
  'day-2': {
    id: 'day-2',
    label: 'Día 2',
    name: 'Full Body B',
    exercises: [
      exercise(
        'goblet-squat',
        'Sentadilla goblet',
        3,
        8,
        10,
        120,
        'Sujeta la mancuerna junto al pecho y baja manteniendo los talones apoyados.',
      ),
      exercise(
        'cable-row',
        'Remo sentado en polea',
        3,
        8,
        12,
        120,
        'Lleva los codos hacia atrás manteniendo el tronco estable, sin tirar con la zona lumbar.',
      ),
      exercise(
        'incline-db-bench',
        'Press inclinado con mancuernas',
        3,
        8,
        12,
        120,
        'Apoya la espalda en el banco inclinado y empuja sin encoger los hombros.',
      ),
      exercise(
        'reverse-lunge',
        'Zancada hacia atrás',
        2,
        8,
        8,
        90,
        'Da un paso atrás y baja con control. Completa las repeticiones con cada pierna.',
        { unilateral: true },
      ),
      exercise(
        'leg-curl',
        'Curl femoral',
        2,
        10,
        12,
        90,
        'Ajusta la máquina y flexiona las rodillas sin levantar la cadera.',
      ),
      exercise(
        'calf-raise',
        'Gemelos de pie',
        2,
        12,
        15,
        60,
        'Eleva los talones y pausa arriba. Baja con control hasta un estiramiento cómodo.',
        { trackOneRM: false },
      ),
      exercise(
        'side-plank',
        'Plancha lateral',
        2,
        20,
        30,
        60,
        'Apoya el antebrazo bajo el hombro. Mantén cadera y tronco alineados por ambos lados.',
        { targetUnit: 'seconds', unilateral: true, trackOneRM: false },
      ),
    ],
  },
};
export const allExercises = Object.values(workoutDays).flatMap(
  (day) => day.exercises,
);
export function targetLabel(e: ExerciseDefinition) {
  return `${e.minReps}${e.maxReps !== e.minReps ? `–${e.maxReps}` : ''} ${e.targetUnit === 'seconds' ? 's' : 'reps'}${e.unilateral ? ' / lado' : ''}`;
}
